### PR TITLE
Added sorting studio list and sorting list item

### PR DESCRIPTION
**Pull request by Wassaf-Shahzad**
#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable
  - [ ] Opened issue for DevOps regarding necessary configuration changes to deployed environments

#### What are the relevant tickets?
(Required)

#### What's this PR do?
(Required)

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Screenshots (if appropriate)
(Optional)

#### What GIF best describes this PR or how it makes you feel?
(Optional)

### CODE REVIEW

**Comment by Wassaf-Shahzad** [comment]
@ChristopherChudzicki @gumaerc Would love your thoughts on the basic implementation.
Also would like your help in the following issue .

Currently repeatable content List is being fetched from redux store and is used to render the content list. The issue is after sorting we need to call a callback (handleDragEnd ) and I am currently a bit stuck in how we use it in Sortable Select.

**Comment by pdpinch** [comment]
@Wassaf-Shahzad please fill in the PR description. Is this related to https://github.com/mitodl/ocw-studio/issues/1635 ?

**Comment by ChristopherChudzicki** [comment]
*Probably would be good to put some high-level answers to questions below in https://github.com/mitodl/ocw-studio/issues/1635.*

This looks like a good start on the sorting UI, but I think there is a little backend work and some UI design decisions to make before we do more UI implementation. 

**Model:** First,`WebsiteContentModel` needs some sort of `weight` field to record the user-specified sort order

**UI Questions:** Also As @gumaerc mentioned [here](https://github.com/mitodl/ocw-hugo-projects/isasues/183#issuecomment-1152734173) there are some issues with regards to searching and pagination. In my opinion:
1. sorting needs to be disabled when there's a search filter applied

    One approach would be to use [Edit], [Order] tabs that [@gumaerc's mock](https://github.com/mitodl/ocw-hugo-projects/issues/183#issuecomment-1152734173) showed. Search would be disabled when the "Order" tab is open. And having a specific "Order" tab would make it more natural to put drag handles on the title cards, indicating that they are sortable.
2. sorting across pages is tricky. We should decide how to handle this, even if we call it out-of-scope for the first iteration of this feature. 

**A new API, maybe?**: Regarding your question
> ...we need to call a callback (handleDragEnd ) and I am currently a bit stuck in how we use it in Sortable Select.
The callback should update the `weight` property of several records. E.g., if we have promos `[P1 ... P10]` then I would expect dragging P6 above P3 to result in 
```
P1       P1
P2       P2
P3       P6     <---\
P4       P3     <---| ... all affected
P5       P4     <---|
P6       P5     <---/
P7       P7
P8       P8
P9       P9
```

We could just make N api requests, but a dedicated API might be better. For one thing, then the swapping logic could live on the backend. (And maybe Django has libraries for this already, e.g., https://django-admin-sortable2.readthedocs.io/en/latest/ ... that seems focused on the admin panel, but maybe is more general purpose than the GIF makes me think.)

**Comment by Wassaf-Shahzad** [comment]
@ChristopherChudzicki @pdpinch  Thanks for looking into this. I do agree we might need to hold off the UI and move to the backend side first. I did some RnD on the handleDragEnd and did figure out that the best approach would be to  change the listing.result order based on moved array.

## Pagination 
In cases like ours where items are being manually sorted (given order by drag and drop) the number of items per collection would be (should be) relatively small. Manually sorting through 30 for 40 items would be bad UX (as per my opinion). However even with this mind, I dont think that we can limit the number of items in an `isSortable` collection. We could implement an infinite scroll view and disable pagination for sortable collections.

## Searching and UI
We could just disable sorting for searching as you recommended but I have recommendation is terms of UI. Rather then having separate buttons for edit and sort modes, collections which have the `isSortable` property could be rendered in the sortable UI (Title card rendered with drag handles) in default and we remove them when searching for pages. This could intuitively give the user context on which items are draggable and which are not.

**Comment by ChristopherChudzicki** [comment]
Closing because we went a slightly different direction. See https://github.com/mitodl/ocw-hugo-projects/issues/183#issuecomment-1402012595

**Pull request closed without merging**
