### PR TITLE
Fix file upload

### LINKED ISSUE #167: Resource file upload is broken on CI
### Steps to Reproduce

Create/edit a resource and try uploading a file.

### Expected Behavior

File is uploaded

### Actual Behavior

Error message: "File is a required field"

Screen Shot 2021-04-01 at 2 08 37 PM

### PR DESCRIPTION
**Pull request by mbertrand**
#### Pre-Flight checklist
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #167 

#### What's this PR do?
Fixes file uploads

#### How should this be manually tested?
- Create two new resources, one with and one without a file.  Both should save successfully.
- Edit a resource, change or add a different file to upload, it should save successfully.

### CODE REVIEW

**Comment by noisecapella** [comment]
I'm not able to create a resource without a file:
Screenshot from 2021-04-01 15-55-15

**Comment by noisecapella** [comment]
Actually, maybe that's desired behavior and the manual testing instructions should be updated? I'm not sure if we are supporting resources without files attached

**Comment by mbertrand** [comment]
If you check the `WebsiteStarter` config in django admin, do those particular fields have `{"required": true}`?

Mine don't so I can leave everything blank.

```
        {
          "label": "Description",
          "name": "description",
          "widget": "text"
        },
        {
          "label": "File",
          "name": "file",
          "widget": "file"
        }
```

**Comment by noisecapella** [comment]
@mbertrand thanks, that was the problem. BTW `site-config-override.yml` does have `required: true` for the file field in resource

**Review by noisecapella — APPROVED** [review]

**Comment by mbertrand** [comment]
Looks like I need to run `manage.py override_site_configs`, thanks for the tip.

**Pull request merged**
