### PR TITLE
ZIP up offline sites in mass-build-sites

### PR DESCRIPTION
**Pull request by gumaerc**
#### Pre-Flight checklist

- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-studio/issues/1476

#### What's this PR do?
In https://github.com/mitodl/ocw-studio/pull/1453, we added the `--offline` flag to the `upsert_mass_build_pipeline` management command, which will upsert an alternate version of the `mass-build-sites` pipeline that uses the `course-offline` theme for generating OCW sites that can be browsed locally on any device. This PR alters the final step of that process, which is syncing the output to S3. The online pipeline will remain the same, but the offline pipeline will now create a ZIP archive of the build output and instead push that up to S3. 

#### How should this be manually tested?
 - First of all, make sure you've taken care of the following prerequisites:
   - `ocw-studio` up and running
   - Minio support configured
   - Concourse support configured
   - Some test courses in your database using the `ocw-course` starter
 - Make a temporary edit to `websites/views.py` to limit the sites seen by `mass-build-sites`:
```
        ...
        sites = sites.prefetch_related("starter").order_by("name")[:10]
        serializer = WebsiteMassBuildSerializer(instance=sites, many=True)
        return Response({"sites": serializer.data})
```
 - Upsert the offline `mass-build-sites` pipeline with `docker-compose exec web ./manage.py upsert_mass_build_pipeline --offline --prefix /offline --starter ocw-course --projects-branch cg/course-v2-testing`
 - Browse to http://concourse:8080 and login with test/test
 - Find the offline `mass-bulid-sites` pipeline we just uploaded and trigger a build
 - After the build completes, browse to http://localhost:9001 and login with your Minio credentials
 - Browse to `ocw-content-live/offline/courses` and look in the various course folders. In there, you should find a ZIP file for each course. Extract one or two of them and double click the `index.html` file to open the course site. Note that these will not include the static resources for each site unless you first upload them to Minio in the appropraite folder in the `ol-ocw-studio-app` bucket before running the pipeline, or if you created the site locally and used Google drive to upload the resources.

### CODE REVIEW

**Review by ChristopherChudzicki — APPROVED** [review]
@gumaerc Thanks for answering my myriad questions about minio and concourse...

The offline mass build succeeded and the zip files were generated. 👍. For the course I created locally, I see the resources.


```
STARTING PUBLISH OF 10-01-ethics-for-engineers-artificial-intelligence-spring-2020
PULLING IN STATIC RESOURCES FOR 10-01-ethics-for-engineers-artificial-intelligence-spring-2020
mv: cannot stat './content/static_resources/*.html': No such file or directory
```
Do we care about that `mv` message?

**Comment by gumaerc** [comment]
> Do we care about that `mv` message?

Hm, good point. This seems to happen if no static resources are present for a site, so the `content/static_resources` folder is never created. I'll experiment with creating that folder before the sync, so it at least exists an an empty folder before that command is run. If it works out I'll commit it.

**Comment by gumaerc** [comment]
@ChristopherChudzicki I added a check to make sure there are any HTML files at that step before attempting to move them. On Monday would you mind running through this one more time to make sure the error is gone?

**Review by ChristopherChudzicki — APPROVED** [review]
👍 After I remembered the upsert the new pipeline, all went well. No mv message.

**Pull request merged**
