### PR TITLE
config,refactor: Add more extensive pre-commit config and lint rules

### PR DESCRIPTION
**Pull request by blarghmatey**
# What are the relevant tickets?
N/A

# Description (What does it do?)
This does a few things:

- Replaces usage of pylint with ruff for linting Python code
- Applies all automated Ruff fixes to the Python code
- Adds noqa comments to all existing linter violations found by Ruff
- Adds Prettier v3.x
- Applies prettier and eslint fixes to all relevant files
- Updates eslint config to be compatible with prettier
- Adds pre-commit rules for running all linters and fixes automatically
- Removes issue and PR templates from the repo so that it will fall back to the ones in mitodl/.github

# How can this be tested?
This was tested by running `pre-commit run --all-files` and ensuring that the output all passes.

# Additional Context
This is related to the proposals outlined in https://github.com/mitodl/hq/discussions/1422

### CODE REVIEW

**Comment by gumaerc** [comment]
Not sure if I'm missing something here, but after rebuilding my containers locally and running `docker compose exec web poetry run ruff --extend-ignore=D1 .` it comes back with 32 errors, all relating to the `# noqa: N999` directives saying that they are unused.

**Comment by blarghmatey** [comment]
How about if you run `pre-commit run --all-files`?

**Comment by blarghmatey** [comment]
And which version of `ruff` is executing inside the container? It should be `0.0.286`

**Comment by gumaerc** [comment]
Also, am I missing something about comment formatting? There are so many `# noqa: E501` tags relating to lines being more than 79 characters wide because of comments. I was doing some reading and `black` has a string reformatter included in the `--preview` flag. I gave it a try and it does reformat single line strings, separating them into multiple lines. However, multi line strings that use the `f""" string """` syntax would simply have the closing triple quote moved to a new line. It also did not reformat single line comments. I'm surprised that there doesn't seem to be a way to use `black` to automatically do a "word wrap" on single line comments, especially if the comment is the only text on a given line. If we're going to ignore the 79 character limit, is there a more uniform way we could do that, rather than inserting these `# noqa: E501` tags everywhere?

**Comment by gumaerc** [comment]
I get the following when running `pre-commit run --all-files`:

```bash
(ocw-studio) gumaerc@gumaerc-laptop:~/Code/ocw-studio$ pre-commit run --all-files
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-prettier:prettier@3.0.3.
[INFO] Initializing environment for https://github.com/scop/pre-commit-shfmt.
[INFO] Initializing environment for https://github.com/scop/pre-commit-shfmt:mvdan.cc/sh/v3/cmd/shfmt@v3.7.0.
[INFO] Initializing environment for https://github.com/astral-sh/ruff-pre-commit.
[INFO] Initializing environment for local.
[INFO] Installing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/scop/pre-commit-shfmt.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/go/bin/go', 'install', 'mvdan.cc/sh/v3/cmd/shfmt@v3.7.0')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    go: downloading mvdan.cc/sh/v3 v3.7.0
    go: downloading golang.org/x/term v0.8.0
    go: downloading github.com/google/renameio/v2 v2.0.0
    go: downloading github.com/pkg/diff v0.0.0-20210226163009-20ebb0f2a09e
    go: downloading mvdan.cc/editorconfig v0.2.0
    go: downloading golang.org/x/sys v0.8.0
    # runtime/internal/sys
    /usr/local/go/src/runtime/internal/sys/consts.go:18:7: DefaultPhysPageSize redeclared in this block
        /usr/local/go/src/runtime/internal/sys/arch_amd64.go:10:2: other declaration of DefaultPhysPageSize
    /usr/local/go/src/runtime/internal/sys/consts.go:22:7: PCQuantum redeclared in this block
        /usr/local/go/src/runtime/internal/sys/arch_amd64.go:11:2: other declaration of PCQuantum
    /usr/local/go/src/runtime/internal/sys/consts.go:25:7: Int64Align redeclared in this block
        /usr/local/go/src/runtime/internal/sys/arch_amd64.go:12:2: other declaration of Int64Align
    /usr/local/go/src/runtime/internal/sys/consts.go:32:7: MinFrameSize redeclared in this block
        /usr/local/go/src/runtime/internal/sys/arch_amd64.go:13:2: other declaration of MinFrameSize
    /usr/local/go/src/runtime/internal/sys/intrinsics_common.go:9:5: len8tab redeclared in this block
        /usr/local/go/src/runtime/internal/sys/intrinsics.go:76:7: other declaration of len8tab
    /usr/local/go/src/runtime/internal/sys/intrinsics_common.go:28:5: ntz8tab redeclared in this block
        /usr/local/go/src/runtime/internal/sys/intrinsics.go:25:7: other declaration of ntz8tab
    /usr/local/go/src/runtime/internal/sys/intrinsics_common.go:48:6: Len64 redeclared in this block
        /usr/local/go/src/runtime/internal/sys/intrinsics.go:99:6: other declaration of Len64
    /usr/local/go/src/runtime/internal/sys/intrinsics_common.go:66:7: m0 redeclared in this block
        /usr/local/go/src/runtime/internal/sys/intrinsics.go:117:7: other declaration of m0
    /usr/local/go/src/runtime/internal/sys/intrinsics_common.go:67:7: m1 redeclared in this block
        /usr/local/go/src/runtime/internal/sys/intrinsics.go:118:7: other declaration of m1
    /usr/local/go/src/runtime/internal/sys/intrinsics_common.go:68:7: m2 redeclared in this block
        /usr/local/go/src/runtime/internal/sys/intrinsics.go:119:7: other declaration of m2
    /usr/local/go/src/runtime/internal/sys/intrinsics_common.go:68:7: too many errors
    # math
    /usr/local/go/src/math/acosh.go:43:6: Acosh defined in both Go and assembly
    /usr/local/go/src/math/asin.go:20:6: Asin defined in both Go and assembly
    /usr/local/go/src/math/asin.go:58:6: Acos defined in both Go and assembly
    /usr/local/go/src/math/asinh.go:40:6: Asinh defined in both Go and assembly
    /usr/local/go/src/math/atan.go:96:6: Atan defined in both Go and assembly
    /usr/local/go/src/math/atan2.go:30:6: Atan2 defined in both Go and assembly
    /usr/local/go/src/math/atanh.go:48:6: Atanh defined in both Go and assembly
    /usr/local/go/src/math/cbrt.go:26:6: Cbrt defined in both Go and assembly
    /usr/local/go/src/math/erf.go:189:6: Erf defined in both Go and assembly
    /usr/local/go/src/math/erf.go:274:6: Erfc defined in both Go and assembly
    /usr/local/go/src/math/erf.go:274:6: too many errors
```

In the container, version 0.0.286 is installed when running `poetry install`:

```bash
(ocw-studio) gumaerc@gumaerc-laptop:~/Code/ocw-studio$ docker compose exec web poetry install
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing ruff (0.0.286)
```

**Comment by blarghmatey** [comment]
All of the noqa comments are generated automatically to address existing linter violations. The intent is that they get addressed incrementally as work happens in those locations.

**Comment by blarghmatey** [comment]
As to the go errors, that is due to the shfmt hook, so it seems that I should set it to use the docker version instead.

**Comment by gumaerc** [comment]
It ran with the latest commit, but now it is detecting errors, but doesn't look it it is when running in Github Actions?

```
/home/gumaerc/Code/ocw-studio/scripts/upgrade_ckeditor.js
  4:7  error  Identifier 'child_process' is not in camel case  camelcase

✖ 1 problem (1 error, 0 warnings)


/home/gumaerc/Code/ocw-studio/hot-reload-dev-server.js
  1:7  error  'path' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


/home/gumaerc/Code/ocw-studio/webpack.config.shared.js
  2:7  error  'webpack' is assigned a value but never used                no-unused-vars
  3:7  error  'CKEditorWebpackPlugin' is assigned a value but never used  no-unused-vars

✖ 2 problems (2 errors, 0 warnings)


scss-lint................................................................Failed
- hook id: scss-lint
- exit code: 2

static/scss/button.scss
 30:1  ✖  Expected selector ".cyan-button" to come    no-descending-specificity
          before selector ".cyan-button:hover"
 36:1  ✖  Expected selector ".cyan-button-outline"    no-descending-specificity
          to come before selector
          ".cyan-button-outline:hover"

2 problems (2 errors, 0 warnings)


static/scss/list.scss
 33:3  ✖  Expected selector "ul.studio-list li" to    no-descending-specificity
          come before selector ".ruled-list
          li:not(:last-child)"

1 problem (1 error, 0 warnings)


static/scss/site-page.scss
 68:3  ✖  Expected selector ".publish-option a" to    no-descending-specificity
          come before selector ".site-page .sidebar
          a"

1 problem (1 error, 0 warnings)
```

**Comment by blarghmatey** [comment]
@gumaerc this is ready for review now

**Comment by gumaerc** [comment]
@blarghmatey This needs another rebase

**Comment by blarghmatey** [comment]
@gumaerc any chance we can make this failing python test more resilient to whitespace changes?

**Comment by gumaerc** [comment]
@blarghmatey The "localdev" functionality honestly hasn't been in practical use since we started this project. We use https://github.com/mitodl/ocw-hugo-projects as our source of truth.

That being said, this test compares the raw contents of the JSON file against the converted contents of the YAML file. As the test itself says, the *contents* should match and the formatting does not matter as long as it is valid JSON. We should instead parse the "raw JSON" file and either deep compare the dictionaries or run `json.dumps` against them both and do the comparison that way. Feel free to do whatever you feel is necessary here.

**Review by gumaerc — APPROVED** [review]
:+1:

**Pull request merged**
