### PR TITLE
Escape quotes in resource link text

### PR DESCRIPTION
**Pull request by ChristopherChudzicki**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What's this PR do?
_This fixes an issue where double quotes in resource links were not being escaped...._

This PR makes the resource link CKEditor plugin use our frontend `Shortcode` class and makes the frontend `Shortcode` class better mirror the `ShortcodeTag` class used in markdown cleanup commands on the backend. In particular, frontend `Shortcode` now un-escapes quotes in parameter values when parsing, and re-escapes them when converting to hugo.

This is important because it means that when our editor sees `{{% resource_link "some-uuid" "title \"with\" escaped quotes" %}}`, we now have an unescaped value to display to user in the WYSIWYG editor. And when the unescaped value is saved, it is re-escaped before being to our API.

#### How should this be manually tested?
On this branch:
1. Create a new resource link or find an existing one. To create a new one, open a page for editing and click "Add link".
2. Edit the link text (move your text cursor into it and start typing) and insert some text with double quotes
3. Save 
4. Inspect the markdown in Django admin. Quotes inside the title should be escaped.
5. Re-open the page. Quotes should not appear escaped to the user.

### CODE REVIEW

**Review by mbertrand — COMMENTED** [review]
The double quotes are getting escaped, but when I reopen the editor for the page nothing shows up.  [Example markdown](https://raw.githubusercontent.com/mbtestorg2022/mb-april-4a/main/content/pages/a-new-page-for-a-new-site.md):

```
{{% resource_link "25e18cbd-a095-4e8c-9c1e-f8614ecbe68d" "\"\"137918 W2C.pdf\"\"" %}}
```

**Comment by mbertrand** [comment]
Screen Shot 2022-04-15 at 12 44 47 PM

**Comment by ChristopherChudzicki** [comment]
@mbertrand Good catch. Looks like this wasn't working with consecutive quotes. Fixed. Please now quote to your heart's content.

**Review by mbertrand — APPROVED** [review]
Works great now! 👍

**Pull request merged**
