### PR TITLE
Add website collection editing functionality

### LINKED ISSUE #357: add UI for editing / creating WebsiteCollections
As a course content author, I'd like to create new collections and edit existing ones.

#### Designs and Mockups

Screen Shot 2021-07-01 at 10 27 58 AM

#### Acceptance Criteria:

- [x] Add / Edit form in a drawer
- [x] fields for editing basic info on the WebsiteCollection (title, description)

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?

closes #357 

#### What's this PR do?

this adds functionality for editing basic attributes of WebsiteCollection records (i.e. their title, description) and for therefore creating new ones.

This does not yet include editing entries in a collection, that will be covered for #376

#### How should this be manually tested?

Visit the collections list page (`/collections`). If you click 'Add' you should get a drawer where you can create a new collection. Then in the list page if you click on the title for a collection you should open an editing drawer where you can change it's title and whatnot.

#### Screenshots (if appropriate)

Screen Shot 2021-07-13 at 10 48 06 AM
Screen Shot 2021-07-13 at 10 48 13 AM
Screen Shot 2021-07-13 at 10 48 21 AM

### CODE REVIEW

**Comment by noisecapella** [comment]
Not sure if this is in scope for this issue since it's about editing but when I click "Save" to add a new collection, the list is not updated with the new collection. If I refresh the browser I see it

**Comment by noisecapella** [comment]
Otherwise functionality looks great

**Comment by aliceriot** [comment]
mm good point, I'll add in a refresh call after the add modal closes

**Comment by aliceriot** [comment]
@noisecapella ok made those changes

**Review by noisecapella — APPROVED** [review]
LGTM :+1:

**Pull request merged**
