### PR TITLE
name offline site zip with short_id instead of name

### PR DESCRIPTION
**Pull request by gumaerc**
#### Pre-Flight checklist

- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-studio/issues/1545

#### What's this PR do?
In https://github.com/mitodl/ocw-studio/pull/1477 we added code to the `mass-bulid-sites` pipeline to create a ZIP archive of the built site at the end of the run when `offline` is true. Currently, the ZIP archive is named with the `Website.name` property. This property is not available in the course metadata published with course sites, however, all the components of `short_id` are. If we simply name the ZIP archives with `short_id` instead, then we can construct URLs to the ZIP archives easily within the theme.

#### How should this be manually tested?
 - First of all, make sure you've taken care of the following prerequisites:
   - `ocw-studio` up and running
   - Minio support configured
   - Concourse support configured
   - Some test courses in your database using the `ocw-course-v2` starter
 - Make a temporary edit to `websites/views.py` to limit the sites seen by `mass-build-sites`:
```
        ...
        sites = Website.objects.filter(name="9-40-introduction-to-neural-computation-spring-2018")
        serializer = WebsiteMassBuildSerializer(instance=sites, many=True)
        return Response({"sites": serializer.data})
```
 - Upsert the offline `mass-build-sites` pipeline with `docker-compose exec web ./manage.py upsert_mass_build_pipeline --offline --starter ocw-course-v2 --projects-branch main --themes-branch main`
 - Browse to http://localhost:9001 and login with your Minio credentials
 - Browse to http://concourse:8080 and login with test/test
 - Find the offline `mass-bulid-sites` pipeline we just uploaded and trigger a build
 - Ensure the build completes without error
 - In the Minio UI, browse to `ol-ocw-studio-app/courses/9-40-introduction-to-neural-computation-spring-2018/ and verify that there is a ZIP file in there with a filename matching the course's `short_id`, which should be `9.40-spring-2018.zip`

### CODE REVIEW

**Review by mbertrand — COMMENTED** [review]
>Upload the static resources into your Minio instance under ol-ocw-studio-app in the courses folder, in a folder with the name being the course id (9-40-introduction-to-neural-computation-spring-2018)

I'm confused by this step.  I created a new site with the `course-v2` starter and synced some resources from gdrive, those resources are in `ol-ocw-studio-app/course/<short_id>` folder in minio.  Are "static resources" referring to something else?  

> In the Minio UI, browse to ol-ocw-studio-app/courses/9-40-introduction-to-neural-computation-spring-2018/ and verify that there is a ZIP file in there with a filename matching the course's short_id

The pipeline ran without errors, processed the site, but there is no zip file for the course under either the `ol-ocw-studio-app` or `ocw-content-live` buckets.  Am I missing a step or configuration setting somewhere?


Screen Shot 2022-10-27 at 8 46 06 AM

The code change itself seem fine, but I can't recreate the expected outcome.

**Review by mbertrand — APPROVED** [review]
Getting the correctly named zip file in the ocw-live bucket now 👍

**Comment by gumaerc** [comment]
For a little bit of extra context here I made a mistake in the testing instructions which has been corrected.  The `--prefix offline` is not necessary and omitting it causes the pipeline to place the zip file alongside the rest of the site content for easy linking

**Review by pt2302 — APPROVED** [review]
Still debugging this on Apple Silicon due to container issues, but everything in the code looks good to me!

**Comment by pt2302** [comment]
Got everything to run and complete successfully on Apple Silicon. 

Wanted to add some more testing instructions for completeness:
- for the "static resources" in the testing instructions above, this refers to a copy of the resources for a given course, from the S3 bucket.
- run the `upsert_theme_assets` pipeline if you have not run it previously, via `docker-compose exec web ./manage.py upsert_theme_assets_pipeline --delete-all`
- make sure that the individual publishing pipeline is upserted, via:
```
docker-compose exec web ./manage.py backpopulate_pipelines --filter 9-40-introduction-to-neural-computation-spring-2018
docker-compose exec web ./manage.py reset_sync_states --filter 9-40-introduction-to-neural-computation-spring-2018 --skip_sync
docker-compose exec web ./manage.py sync_website_to_backend --filter 9-40-introduction-to-neural-computation-spring-2018
```
- publish the course on your local instance of OCW Studio using the Publish UI.
- Run the (modified to only run on one particular course, as above) `upsert_mass_build_pipeline` via `docker-compose exec web ./manage.py upsert_mass_build_pipeline --offline --starter ocw-course-v2 --projects-branch main --themes-branch main --delete-all`.

**Pull request merged**
